//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPruebasDev.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNOS
    {
        public int Matricula { get; set; }
        public string NombreAlumno { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Telefono { get; set; }
        public int IDCarrera { get; set; }
        public int IDGrupo { get; set; }
    
        public virtual CARRERAS CARRERAS { get; set; }
        public virtual GRUPOS GRUPOS { get; set; }
    }
}
