//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPruebasDev.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNOS
    {
        public string Matricula { get; set; }
        public string NombreAlumno { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Correo { get; set; }
        public string Contrasenia { get; set; }
        public string Telefono { get; set; }
        public bool Status { get; set; }
        public int IDCarrera { get; set; }
        public int IDGrupo { get; set; }
    
        public virtual CARRERAS CARRERAS { get; set; }
        public virtual GRUPOS GRUPOS { get; set; }
    }
}
