//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPruebasDev.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORA
    {
        public int CLAVE { get; set; }
        public string PK { get; set; }
        public string ACCION { get; set; }
        public string TABLA { get; set; }
        public string CAMPO { get; set; }
        public string VALORORIGINAL { get; set; }
        public string VALORNUEVO { get; set; }
        public System.DateTime FECHA { get; set; }
        public string USUARIO { get; set; }
    }
}
