//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPruebasDev.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDPruebasEntities : DbContext
    {
        public BDPruebasEntities()
            : base("name=BDPruebasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALUMNOS> ALUMNOS { get; set; }
        public virtual DbSet<CARRERAS> CARRERAS { get; set; }
        public virtual DbSet<DIVISIONES> DIVISIONES { get; set; }
        public virtual DbSet<GRUPOS> GRUPOS { get; set; }
        public virtual DbSet<VistaAlumnos> VistaAlumnos { get; set; }
        public virtual DbSet<VistaCarreras> VistaCarreras { get; set; }
        public virtual DbSet<VistaDivisiones> VistaDivisiones { get; set; }
        public virtual DbSet<VistaGrupos> VistaGrupos { get; set; }
    }
}
