//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPruebasDev.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDPruebasEntities : DbContext
    {
        public BDPruebasEntities()
            : base("name=BDPruebasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALUMNOS> ALUMNOS { get; set; }
        public virtual DbSet<CARRERAS> CARRERAS { get; set; }
        public virtual DbSet<DIVISIONES> DIVISIONES { get; set; }
        public virtual DbSet<GRUPOS> GRUPOS { get; set; }
        public virtual DbSet<VistaAlumnos> VistaAlumnos { get; set; }
        public virtual DbSet<VistaCarreras> VistaCarreras { get; set; }
        public virtual DbSet<VistaDivisiones> VistaDivisiones { get; set; }
        public virtual DbSet<VistaGrupos> VistaGrupos { get; set; }
    }
}
