//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPruebasDev.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTADIVISIONES
    {
        public int IDDivision { get; set; }
        public string NombreDivision { get; set; }
        public bool Status { get; set; }
    }
}
