//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPruebasDev.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTAALUMNOS
    {
        public string Matricula { get; set; }
        public string NombreCompleto { get; set; }
        public string Correo { get; set; }
        public string Contrasenia { get; set; }
        public string Telefono { get; set; }
        public string NombreCarrera { get; set; }
        public string GradoGrupo { get; set; }
        public bool Status { get; set; }
    }
}
